# Colors Configuration for Hotel Stern
# 
# This file contains centralized color definitions for the hotel website.
# All section-specific colors are defined here and can be imported by colors.js.
# 
# Moving colors to YAML allows for easier configuration without modifying code.

# Theme colors - A refined, elegant hotel palette
themeColors:
  # Primary and secondary theme colors
  primary:
    light: '#305F85'  # Refined navy blue - sophisticated and serene
    dark: '#6B9AC4'   # Lighter blue for dark mode
  
  secondary:
    light: '#38A18C'  # Rich teal - elegant and refreshing
    dark: '#FFEB3B'   # TEMPORARY: Yellow for debugging secondary-dark color issues
  
  # Background colors
  background:
    light: '#D8D0C8'  # Darker warm taupe - creates depth for the page background
    dark: '#0F161F'   # Nearly black blue for immersive dark mode
  
  paper:
    light: '#F8F8F8'  # Slight off-white for sections with contrast to background
    dark: '#1F2937'   # Darker blue-gray for sections in dark mode
  
  # Text colors
  text:
    light: '#2C3E50'  # Deep navy-charcoal - refined and elegant
    dark: '#FF7F00 '   # TEMPORARY: Purple for debugging text-dark color issues
  
  textSecondary:
    light: '#566573'  # Slate gray for secondary text - sophisticated
    dark: '#A0AEC0'   # Muted blue-gray for dark mode
  
  # Accent colors (warm contrast to cool primary/secondary)
  accent:
    light: '#D4A15A'  # Muted gold - premium and subtle
    dark: '#F6C066'   # Lighter gold for dark mode
  
  # Button colors
  primarybutton:
    light: '#305F85'  # Match primary
    dark: '#3A6B96'   # Darker blue for better contrast with white text
  
  primarybuttontext:
    light: '#FFFFFF'  # White on blue buttons
    dark: '#FFFFFF'   # White on blue buttons
  
  secondarybutton:
    light: '#FFFFFF'  # White background
    dark: '#253649'   # Dark paper color
  
  secondarybuttontext:
    light: '#305F85'  # Primary color text
    dark: '#E2E8F0'   # Light text
  
  # Special buttons (for specific UI components)
  button:
    light: '#F0F8FF'  # Very light blue background
    dark: '#1F354A'   # Darker navy for dark mode with better contrast
  
  buttontext:
    light: '#305F85'  # Primary blue for text in light mode
    dark: '#E2F0FF'   # Brighter blue text for dark mode for better contrast
  
  # Header and menu colors
  heading:
    light: '#2C3E50'  # Deep navy-charcoal
    dark: '#E2E8F0'   # Soft white
  
  menu:
    light: '#F9F7F2'  # Background light
    dark: '#1A2639'   # Background dark
  
  menutext:
    light: '#2C3E50'  # Text light
    dark: '#E2E8F0'   # Text dark
  
  menuaccent:
    light: '#305F85'  # Primary light
    dark: '#6B9AC4'   # Primary dark
  
  # Section header colors
  sectionheader:
    light: '#305F85'  # Using primary blue for consistent branding in headers
    dark: '#6B9AC4'   # Matching dark mode primary for better visual harmony
  
  sectionsubheader:
    light: '#38A18C'  # Using secondary teal for consistent styling
    dark: '#67D5B5'   # Matching dark mode secondary for better consistency

# Base colors (section-specific configurations)
colors:
  # Hero section colors
  hero:
    mainText:
      background: 'secondary-light'
      darkModeBackground: 'primary-dark'  # Using brighter blue for better visibility
      opacity: '85'
      darkModeOpacity: '90'  # Slightly reduced opacity for better readability
      textColor: 'paper-light'  # Brighter white for better contrast
      darkModeTextColor: 'paper-light'  # Ensuring consistent bright text in dark mode
    
    subTitle:
      background: 'paper-light'
      darkModeBackground: 'accent-dark'  # Using the brighter gold for better visibility
      opacity: '85'
      darkModeOpacity: '85'  # Lower opacity for better visibility of background images
      textColor: 'text-light'
      darkModeTextColor: 'paper-light'  # Ensuring bright text that's easy to read
  
  # Section block colors
  sectionBlock:
    header:
      color: 'sectionheader-light'
      darkModeColor: 'sectionheader-dark'
    
    subheader:
      color: 'sectionsubheader-light'
      darkModeColor: 'sectionsubheader-dark'
  
  # FAQ section colors
  faq:
    question:
      background: 'paper-light'
      darkModeBackground: 'paper-dark'
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      borderColor: 'accent-light'
      darkModeBorderColor: 'accent-dark'
    
    questionOpened:
      background: 'secondary-light'
      darkModeBackground: 'secondary-dark'
      textColor: 'paper-light'
      darkModeTextColor: 'paper-light'
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
    
    answer:
      background: 'paper-light'
      darkModeBackground: 'paper-dark'
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      borderColor: 'accent-light'
      darkModeBorderColor: 'accent-dark'
  
  # Chatbot section colors
  chatbot:
    userMessage:
      background: 'primary-light'  # Darker blue for better contrast with white text
      darkModeBackground: 'background-dark'
      textColor: 'primarybuttontext-light'
      darkModeTextColor: 'primarybuttontext-dark'
      timeColor: 'text-light'  # Darker text for better contrast
      darkModeTimeColor: 'gray-300'  # Lighter color for dark mode contrast
    
    botMessage:
      background: 'primary-light'
      darkModeBackground: 'secondary-dark'  # Using secondary-dark for better contrast
      textColor: 'primarybuttontext-light'
      darkModeTextColor: 'primarybuttontext-dark'
      timeColor: 'text-light'  # Darker text for better contrast
      darkModeTimeColor: 'gray-300'  # Lighter color for dark mode contrast
    
    container:
      background: 'paper-light'
      darkModeBackground: 'paper-dark'
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
    
    inputField:
      background: 'paper-light'
      darkModeBackground: 'paper-dark'
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
  
  # PictureGallery section colors
  pictureGallery:
    caption:
      background: 'secondary-light'
      darkModeBackground: 'paper-dark'
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
  
  # Room card colors
  roomCard:
    background: 'white'
    darkModeBackground: 'gray-800'
    textColor: 'gray-900'
    darkModeTextColor: 'gray-100'
    borderColor: 'gray-200'
    darkModeBorderColor: 'gray-700'
    
    # Variations for different room types
    standard:
      background: 'white'
      darkModeBackground: 'gray-800'
    
    deluxe:
      background: 'amber-50'
      darkModeBackground: 'amber-900'
    
    suite:
      background: 'emerald-50'
      darkModeBackground: 'emerald-900'
  
  # Team section colors
  team:
    card:
      background: 'white'
      darkModeBackground: 'gray-800'
      hoverEffect: 'scale-[1.02]'
      shadow: 'shadow-lg'
      darkModeShadow: 'shadow-xl'
    
    name:
      color: 'blue-800'  # Deep blue (formerly #2c5282)
      darkModeColor: 'teal-300'  # Fixed invalid color 'yellowteal-300'
    
    title:
      color: 'gray-600'  # Slate gray (formerly #4a5568)
      darkModeColor: 'gray-400'
    
    citation:
      gradientFrom: 'blue-700'  # Lightened from blue-900 for better contrast with text
      gradientTo: 'blue-600'  # Lightened from blue-800 for better contrast with text
      darkModeGradientFrom: 'gray-800'
      darkModeGradientTo: 'gray-700'
      textColor: 'white'  # Pure white for maximum contrast
      darkModeTextColor: 'gray-100'
      glowColor: 'blue-700'  # Used for the hover glow effect
      darkModeGlowColor: 'blue-500'
  
  # Section-specific background colors
  # These are used by the SectionBlock component when sectionType is specified
  sections:
    default:
      background: 'paper-light'  # White background for sections
      darkModeBackground: 'paper-dark'  # Dark paper background for dark mode
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
    
    team:
      background: 'paper-light'  # Using theme variable
      darkModeBackground: 'paper-dark'  # Using theme variable
      borderColor: 'secondary-light'  # Teal accents for team section
      darkModeBorderColor: 'secondary-dark'  # Matching dark mode secondary
    
    faq:
      background: 'paper-light'  # Crisp white background for questions
      darkModeBackground: 'paper-dark'  # Matching dark mode paper
      borderColor: 'accent-light'  # Warm gold accent border
      darkModeBorderColor: 'accent-dark'  # Matching dark mode accent
    
    pictureGallery:
      background: 'paper-light'  # Using theme variable
      darkModeBackground: 'paper-dark'  # Using theme variable
      borderColor: 'primary-light'  # Primary blue borders for gallery
      darkModeBorderColor: 'primary-dark'  # Matching dark mode primary
    
    rooms:
      background: 'background-light'  # Using theme variable
      darkModeBackground: 'background-dark'  # Using theme variable
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
    
    services:
      background: 'paper-light'  # Using theme variable
      darkModeBackground: 'paper-dark'  # Using theme variable
      borderColor: 'accent-light'
      darkModeBorderColor: 'accent-dark'
    
    testimonials:
      background: 'background-light'  # Using theme variable
      darkModeBackground: 'background-dark'  # Using theme variable
      borderColor: 'primary-light'
      darkModeBorderColor: 'primary-dark'
    
    contact:
      background: 'paper-light'  # Using theme variable
      darkModeBackground: 'paper-dark'  # Using theme variable
      borderColor: 'secondary-light'
      darkModeBorderColor: 'secondary-dark'
    
    map:
      background: 'background-light'  # Using theme variable
      darkModeBackground: 'background-dark'  # Using theme variable
      borderColor: 'primary-light'
      darkModeBorderColor: 'primary-dark'
  
  # Table colors
  table:
    headerBg: 'accent-light'
    darkModeHeaderBg: 'accent-dark'
    headerText: 'paper-light'  # White text on dark headers
    darkModeHeaderText: 'paper-light'
    rowEvenBg: 'paper-light'
    darkModeRowEvenBg: 'paper-dark'
    rowOddBg: 'background-light'
    darkModeRowOddBg: 'background-dark'
    cellText: 'text-light'
    darkModeCellText: 'text-dark'
    border: 'gray-300'
    darkModeBorder: 'gray-700'
  
  # Form element colors
  form:
    input:
      background: 'paper-light'
      darkModeBackground: 'paper-dark'
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      borderColor: 'gray-300'
      darkModeBorderColor: 'gray-600'
      focusBorderColor: 'primary-light'
      darkModeFocusBorderColor: 'primary-dark'
    
    label:
      textColor: 'text-light'
      darkModeTextColor: 'text-dark'
      requiredColor: 'accent-light'
      darkModeRequiredColor: 'accent-dark'
    
    button:
      background: 'primary-light'
      darkModeBackground: 'primary-dark'
      textColor: 'paper-light'
      darkModeTextColor: 'paper-light'
      hoverBackground: 'accent-light'
      darkModeHoverBackground: 'accent-dark'
    
    error:
      textColor: 'red-600'
      darkModeTextColor: 'red-400'
      borderColor: 'red-300'
      darkModeBorderColor: 'red-800'
  
  # Layout utility colors
  layout:
    divider: 'gray-200'
    darkModeDivider: 'gray-700'
    shadow: 'shadow-md'
    darkModeShadow: 'shadow-xl'
    border: 'gray-200'
    darkModeBorder: 'gray-700'
  
  # Pricing colors
  pricing:
    currency: 'text-light'
    darkModeCurrency: 'text-dark'
    amount: 'secondary-light'
    darkModeAmount: 'secondary-dark'
    discount: 'accent-light'
    darkModeDiscount: 'accent-dark'
    savedAmount: 'green-600'
    darkModeSavedAmount: 'green-400'
  
  # Call to action colors
  cta:
    background: 'accent-light'
    darkModeBackground: 'accent-dark'
    textColor: 'paper-light'
    darkModeTextColor: 'paper-light'
    buttonBackground: 'primary-light'
    darkModeButtonBackground: 'primary-dark'
    buttonText: 'paper-light'
    darkModeButtonText: 'paper-light'

  # PictureGallery tailwind classes
  'pictureGallery-caption-bg': 'bg-secondary-light dark:bg-paper-dark'
  'pictureGallery-caption-border': 'border-secondary-light dark:border-secondary-dark'
  'pictureGallery-caption-text': 'text-text-light dark:text-text-dark'
