# Font Sizes Configuration for POS Hotel Property
# 
# This file contains custom font size definitions specific to the POS property.
# All section-specific font sizes are defined here and can be imported by fontSizes.js.
# 
# Property-specific YAML allows each property to have its own visual identity.

# Heading font sizes
h1: '2.2rem'   # 44px - slightly larger than SZS
h2: '2rem'     # 40px - same as SZS
h3: '1.6rem'   # 32px - slightly larger than SZS
h4: '1.4rem'   # 28px - slightly larger than SZS
h5: '1.25rem'  # 25px - same as SZS
h6: '1.1rem'   # 22px - same as SZS

# Body text sizes
body:
  xs: '0.75rem'  # 15px
  sm: '0.875rem' # 17.5px
  base: '1rem'   # 20px
  lg: '1.125rem' # 22.5px
  xl: '1.25rem'  # 25px

# Responsive text sizes for rich text content
rich:
  desktop: '1.7rem'   # 34px for large screens - slightly larger than SZS
  tablet: '1.5rem'    # 30px for medium screens - slightly larger than SZS
  mobile: '1.3rem'    # 26px for small screens - slightly larger than SZS

# Special element sizes
button: '1rem'       # 20px
caption: '0.875rem'  # 17.5px
label: '0.875rem'    # 17.5px
price: '1.3rem'      # 26px - slightly larger than SZS
badge: '0.8rem'      # 16px - slightly larger than SZS

# Section header sizes
section:
  header: '38px'     # 38px - slightly larger than SZS
  subheader: '1.6rem'  # 32px - slightly larger than SZS

# FAQ section sizes
faq:
  question: '1.1rem'     # 22px - slightly larger than SZS
  questionMobile: '1rem' # 20px for mobile
  answer: '1rem'         # 20px
  answerMd: '1rem'       # 20px for medium screens and up

# Debug and utility sizes
debug: '0.6rem'      # 12px
