# Font Configuration for SEH Hotel Property
# 
# This file contains font selection configuration specific to the SEH property.
# Property-specific YAML allows each property to have its own typography identity.

# Selected font combination (1-23)
selectedFontCombination: 17

# Debug mode
debugFonts: false
