# Font Configuration for SHH Hotel Property
# 
# This file contains font selection configuration specific to the SHH property.
# Property-specific YAML allows each property to have its own typography identity.

# Selected font combination (1-23)
selectedFontCombination: 2

# Debug mode
debugFonts: false
