# Font Configuration for SZS Hotel Property
# 
# This file contains font selection configuration specific to the SZS property.
# Property-specific YAML allows each property to have its own typography identity.

# Selected font combination (1-23)
selectedFontCombination: 13

# Debug mode
debugFonts: false
